DROP DATABASE IF EXISTS shoe_store_database;

CREATE DATABASE shoe_store_database;

USE shoe_store_database;

CREATE TABLE staffs(
	id INT AUTO_INCREMENT PRIMARY KEY,
	staff_code VARCHAR(100) UNIQUE NOT NULL,
	full_name VARCHAR(255) CHARACTER SET UTF8MB4 COLLATE UTF8MB4_UNICODE_CI DEFAULT '',
	gender VARCHAR(10) CHARACTER SET UTF8MB4 COLLATE UTF8MB4_UNICODE_CI DEFAULT '',
	birthday DATE DEFAULT CURRENT_DATE,
	phone_number VARCHAR(13) UNIQUE NOT NULL,
	address VARCHAR(255) CHARACTER SET UTF8MB4 COLLATE UTF8MB4_UNICODE_CI DEFAULT '',
	email VARCHAR(255) UNIQUE NOT NULL, 
	password VARCHAR(255) DEFAULT '',
	role VARCHAR(10) NOT NULL,
	created_at DATETIME DEFAULT CURRENT_DATE,
	updated_at DATETIME DEFAULT CURRENT_DATE,
	is_active TINYINT(1) DEFAULT 1
);

CREATE TABLE customers(
	id INT AUTO_INCREMENT PRIMARY KEY,
	customer_code VARCHAR(100) UNIQUE NOT NULL,
	full_name VARCHAR(255) CHARACTER SET UTF8MB4 COLLATE UTF8MB4_UNICODE_CI DEFAULT '',
	gender VARCHAR(10) CHARACTER SET UTF8MB4 COLLATE UTF8MB4_UNICODE_CI DEFAULT '',
	birthday DATE DEFAULT CURRENT_DATE,
	phone_number VARCHAR(13) UNIQUE NOT NULL,
	address VARCHAR(255) CHARACTER SET UTF8MB4 COLLATE UTF8MB4_UNICODE_CI DEFAULT '',
	email VARCHAR(255) UNIQUE NOT NULL, 
	password VARCHAR(255) DEFAULT '',
	created_at DATETIME DEFAULT CURRENT_DATE,
	updated_at DATETIME DEFAULT CURRENT_DATE
);

CREATE TABLE address_customer(
	id INT AUTO_INCREMENT PRIMARY KEY,
	id_customer INT NOT NULL,
	customer_name VARCHAR(255) CHARACTER SET UTF8MB4 COLLATE UTF8MB4_UNICODE_CI DEFAULT '',
	phone_number VARCHAR(13) NOT NULL,
	address VARCHAR(255) CHARACTER SET UTF8MB4 COLLATE UTF8MB4_UNICODE_CI DEFAULT '',
	CONSTRAINT FK_address_customer FOREIGN KEY(id_customer) REFERENCES customers(id) 
	ON UPDATE CASCADE 
	ON DELETE CASCADE
);

CREATE TABLE brands(
	id INT AUTO_INCREMENT PRIMARY KEY,
	brand_code VARCHAR(100) UNIQUE NOT NULL,
	brand_name VARCHAR(255) CHARACTER SET UTF8MB4 COLLATE UTF8MB4_UNICODE_CI DEFAULT '',
	description VARCHAR(255) DEFAULT ''
);

CREATE TABLE categories(
	id INT AUTO_INCREMENT PRIMARY KEY,
	category_code VARCHAR(100) UNIQUE NOT NULL,
	category_name VARCHAR(255) CHARACTER SET UTF8MB4 COLLATE UTF8MB4_UNICODE_CI DEFAULT '',
	description VARCHAR(255) DEFAULT ''
);

CREATE TABLE materials(
	id INT AUTO_INCREMENT PRIMARY KEY,
	material_code VARCHAR(100) UNIQUE NOT NULL,
	material_name VARCHAR(255) CHARACTER SET UTF8MB4 COLLATE UTF8MB4_UNICODE_CI DEFAULT '',
	description VARCHAR(255) DEFAULT ''
);

CREATE TABLE soles(
	id INT AUTO_INCREMENT PRIMARY KEY,
	sole_code VARCHAR(100) UNIQUE NOT NULL,
	sole_name VARCHAR(255) CHARACTER SET UTF8MB4 COLLATE UTF8MB4_UNICODE_CI DEFAULT '',
	description VARCHAR(255) DEFAULT ''
);

CREATE TABLE colors(
	id INT AUTO_INCREMENT PRIMARY KEY,
	color_code VARCHAR(100) UNIQUE NOT NULL,
	color_name VARCHAR(255) CHARACTER SET UTF8MB4 COLLATE UTF8MB4_UNICODE_CI DEFAULT '',
	description VARCHAR(255) DEFAULT ''
);

CREATE TABLE sizes(
	id INT AUTO_INCREMENT PRIMARY KEY,
	size_code VARCHAR(100) UNIQUE NOT NULL,
	size_name VARCHAR(255) CHARACTER SET UTF8MB4 COLLATE UTF8MB4_UNICODE_CI DEFAULT '',
	description VARCHAR(255) DEFAULT ''
);


CREATE TABLE coupons(
	id INT AUTO_INCREMENT PRIMARY KEY,
	coupons_code VARCHAR(100) UNIQUE NOT NULL,
	conditions DECIMAL(65,5) DEFAULT 0,
	coupons_price DECIMAL(65,5) DEFAULT 0,
	quantity INT DEFAULT 0,
	start_date DATETIME DEFAULT CURRENT_DATE,
	end_date DATETIME DEFAULT CURRENT_DATE,
	created_at DATETIME DEFAULT CURRENT_DATE,
	updated_at DATETIME DEFAULT CURRENT_DATE,
	is_active TINYINT(1) DEFAULT 1
);

CREATE TABLE sales(
	id INT AUTO_INCREMENT PRIMARY KEY,
	sale_code VARCHAR(100) UNIQUE NOT NULL,
	sale_name VARCHAR(255) CHARACTER SET UTF8MB4 COLLATE UTF8MB4_UNICODE_CI DEFAULT '',
	percent FLOAT DEFAULT 0,
	start_date DATETIME DEFAULT CURRENT_DATE,
	end_date DATETIME DEFAULT CURRENT_DATE,
	created_at DATETIME DEFAULT CURRENT_DATE,
	updated_at DATETIME DEFAULT CURRENT_DATE,
	is_active TINYINT(1) DEFAULT 1
);

CREATE TABLE products(
	id INT AUTO_INCREMENT PRIMARY KEY,
	product_code VARCHAR(100) UNIQUE NOT NULL,
	product_name VARCHAR(255) CHARACTER SET UTF8MB4 COLLATE UTF8MB4_UNICODE_CI DEFAULT '',
	id_brand INT NOT NULL,
	id_category INT NOT NULL,
	id_sole INT NOT NULL,
	id_material INT NOT NULL,
	created_at DATETIME DEFAULT CURRENT_DATE,
	updated_at DATETIME DEFAULT CURRENT_DATE,
	CONSTRAINT FK_product_brand FOREIGN KEY(id_brand) REFERENCES brands(id) 
	ON UPDATE CASCADE 
	ON DELETE CASCADE,
	CONSTRAINT FK_product_category FOREIGN KEY(id_category) REFERENCES categories(id) 
	ON UPDATE CASCADE 
	ON DELETE CASCADE,
	CONSTRAINT FK_product_sole FOREIGN KEY(id_sole) REFERENCES soles(id) 
	ON UPDATE CASCADE 
	ON DELETE CASCADE,
	CONSTRAINT FK_product_material FOREIGN KEY(id_material) REFERENCES materials(id) 
	ON UPDATE CASCADE 
	ON DELETE CASCADE
);

CREATE TABLE product_images(
	id INT AUTO_INCREMENT PRIMARY KEY,
	id_product INT NOT NULL,
	images VARCHAR(255) DEFAULT '',
	CONSTRAINT FK_images_product FOREIGN KEY(id_product) REFERENCES products(id) 
	ON UPDATE CASCADE 
	ON DELETE CASCADE
);

CREATE TABLE product_details(
	id INT AUTO_INCREMENT PRIMARY KEY,
	id_product INT NOT NULL,
	id_color INT NOT NULL,
	id_size INT NOT NULL,
	id_sale INT NOT NULL,
	weight FLOAT DEFAULT 0,
	price_old DECIMAL(65,5) DEFAULT 0,
	price_new DECIMAL(65,5) DEFAULT 0,
	quantity INT DEFAULT 0,
	status VARCHAR(30) CHARACTER SET UTF8MB4 COLLATE UTF8MB4_UNICODE_CI DEFAULT '',
	created_at DATETIME DEFAULT CURRENT_DATE,
	updated_at DATETIME DEFAULT CURRENT_DATE,
	CONSTRAINT FK_productDetails_product FOREIGN KEY(id_product) REFERENCES products(id) 
	ON UPDATE CASCADE 
	ON DELETE CASCADE,
	CONSTRAINT FK_productDetails_color FOREIGN KEY(id_color) REFERENCES colors(id) 
	ON UPDATE CASCADE 
	ON DELETE CASCADE,
	CONSTRAINT FK_productDetails_size FOREIGN KEY(id_size) REFERENCES sizes(id) 
	ON UPDATE CASCADE 
	ON DELETE CASCADE,
	CONSTRAINT FK_productDetails_sale FOREIGN KEY(id_sale) REFERENCES sales(id) 
	ON UPDATE CASCADE 
	ON DELETE CASCADE
);

CREATE TABLE history_sales(
	id INT AUTO_INCREMENT PRIMARY KEY,
	id_product_details INT NOT NULL,
	id_sale INT NOT NULL,
	is_active TINYINT(1) DEFAULT 1,
	CONSTRAINT FK_history_sale_productDetails FOREIGN KEY(id_product_details) REFERENCES product_details(id) 
	ON UPDATE CASCADE 
	ON DELETE CASCADE,
	CONSTRAINT FK_history_sale_sales FOREIGN KEY(id_sale) REFERENCES sales(id) 
	ON UPDATE CASCADE 
	ON DELETE CASCADE
);

CREATE TABLE carts(
	id INT AUTO_INCREMENT PRIMARY KEY,
	id_customer INT NOT NULL,
	id_product_details INT NOT NULL,
	quantity INT DEFAULT 0,
	created_at DATETIME DEFAULT CURRENT_DATE,
	updated_at DATETIME DEFAULT CURRENT_DATE,
	CONSTRAINT FK_cart_customer FOREIGN KEY(id_customer) REFERENCES customers(id) 
	ON UPDATE CASCADE 
	ON DELETE CASCADE,
	CONSTRAINT FK_cart_productDetails FOREIGN KEY(id_product_details) REFERENCES product_details(id) 
	ON UPDATE CASCADE 
	ON DELETE CASCADE
);

CREATE TABLE comments(
	id INT AUTO_INCREMENT PRIMARY KEY,
	id_customer INT NOT NULL,
	id_product_details INT NOT NULL,
	comment VARCHAR(255) CHARACTER SET UTF8MB4 COLLATE UTF8MB4_UNICODE_CI DEFAULT '',
	CONSTRAINT FK_comments_customer FOREIGN KEY(id_customer) REFERENCES customers(id) 
	ON UPDATE CASCADE 
	ON DELETE CASCADE,
	CONSTRAINT FK_comments_productDetails FOREIGN KEY(id_product_details) REFERENCES product_details(id) 
	ON UPDATE CASCADE 
	ON DELETE CASCADE
);

CREATE TABLE orders(
	id INT AUTO_INCREMENT PRIMARY KEY,
	order_code VARCHAR(100) UNIQUE NOT NULL,
	id_customer INT NULL,
	id_staff INT NOT NULL,
	id_coupons INT NULL,
	customer_name VARCHAR(100) CHARACTER SET UTF8MB4 COLLATE UTF8MB4_UNICODE_CI DEFAULT '',
	phone_number VARCHAR(13) DEFAULT '',
	address VARCHAR(255) CHARACTER SET UTF8MB4 COLLATE UTF8MB4_UNICODE_CI DEFAULT '',
	transport_price DECIMAL(65,5) DEFAULT 0,
	reduced_price DECIMAL(65,5) DEFAULT 0,
	total_price DECIMAL(65,5) DEFAULT 0,
	total_payouts DECIMAL(65,5) DEFAULT 0,
	order_type VARCHAR(255) DEFAULT '',
	status VARCHAR(255) DEFAULT '',
	created_at DATETIME DEFAULT CURRENT_DATE,
	updated_at DATETIME DEFAULT CURRENT_DATE,
	CONSTRAINT FK_orders_customer FOREIGN KEY(id_customer) REFERENCES customers(id) 
	ON UPDATE CASCADE 
	ON DELETE CASCADE,
	CONSTRAINT FK_orders_staff FOREIGN KEY(id_staff) REFERENCES staffs(id) 
	ON UPDATE CASCADE 
	ON DELETE CASCADE,
	CONSTRAINT FK_orders_coupons FOREIGN KEY(id_coupons) REFERENCES coupons(id) 
	ON UPDATE CASCADE 
	ON DELETE CASCADE
);

CREATE TABLE order_details(
	id INT AUTO_INCREMENT PRIMARY KEY,
	id_product_details INT NOT NULL,
	id_orders INT NOT NULL,
	quantity INT DEFAULT 0,
	total_price DECIMAL(65,5) DEFAULT 0,
	status VARCHAR(255) DEFAULT '',
	CONSTRAINT FK_orderDetails_productDetails FOREIGN KEY(id_product_details) REFERENCES product_details(id) 
	ON UPDATE CASCADE 
	ON DELETE CASCADE,
	CONSTRAINT FK_orderDetails_orders FOREIGN KEY(id_orders) REFERENCES orders(id) 
	ON UPDATE CASCADE 
	ON DELETE CASCADE
);

CREATE TABLE order_history(
	id INT AUTO_INCREMENT PRIMARY KEY,
	id_orders INT NOT NULL,
	description VARCHAR(255) CHARACTER SET UTF8MB4 COLLATE UTF8MB4_UNICODE_CI DEFAULT '',
	changed_time DATETIME DEFAULT CURRENT_DATE,
	CONSTRAINT FK_orderHistory_orders FOREIGN KEY(id_orders) REFERENCES orders(id) 
	ON UPDATE CASCADE 
	ON DELETE CASCADE
);
