DROP DATABASE IF EXISTS sneak_zonedb;

CREATE DATABASE sneak_zonedb;

USE sneak_zonedb;

CREATE TABLE staffs(
	id VARCHAR(255) PRIMARY KEY DEFAULT (UUID()),
	staff_code VARCHAR(100) UNIQUE NOT NULL,
	full_name VARCHAR(255) CHARACTER SET UTF8MB4 COLLATE UTF8MB4_UNICODE_CI DEFAULT '',
	gender VARCHAR(10) CHARACTER SET UTF8MB4 COLLATE UTF8MB4_UNICODE_CI DEFAULT '',
	birthday DATE DEFAULT CURRENT_DATE,
	phone_number VARCHAR(13) UNIQUE NOT NULL,
	address VARCHAR(255) CHARACTER SET UTF8MB4 COLLATE UTF8MB4_UNICODE_CI DEFAULT '',
	email VARCHAR(255) UNIQUE NOT NULL, 
	username VARCHAR(255) UNIQUE NOT NULL,
	password VARCHAR(255) DEFAULT '',
	role VARCHAR(10) NOT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	is_active TINYINT(1) DEFAULT 1
);

CREATE TABLE customers(
	id VARCHAR(255) PRIMARY KEY DEFAULT (UUID()),
	customer_code VARCHAR(100) UNIQUE NOT NULL,
	full_name VARCHAR(255) CHARACTER SET UTF8MB4 COLLATE UTF8MB4_UNICODE_CI DEFAULT '',
	gender VARCHAR(10) CHARACTER SET UTF8MB4 COLLATE UTF8MB4_UNICODE_CI DEFAULT '',
	birthday DATE DEFAULT CURRENT_DATE,
	phone_number VARCHAR(13) UNIQUE NOT NULL,
	address VARCHAR(255) CHARACTER SET UTF8MB4 COLLATE UTF8MB4_UNICODE_CI DEFAULT '',
	email VARCHAR(255) UNIQUE NOT NULL, 
  	password VARCHAR(255) DEFAULT '',
	accumulated_points DECIMAL(65,5) DEFAULT 0,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE address_customer(
	id VARCHAR(255) PRIMARY KEY DEFAULT (UUID()),
	id_customer VARCHAR(255) NOT NULL,
	customer_name VARCHAR(255) CHARACTER SET UTF8MB4 COLLATE UTF8MB4_UNICODE_CI DEFAULT '',
	phone_number VARCHAR(13) NOT NULL,
	address VARCHAR(255) CHARACTER SET UTF8MB4 COLLATE UTF8MB4_UNICODE_CI DEFAULT '',
	CONSTRAINT FK_address_customer FOREIGN KEY(id_customer) REFERENCES customers(id) 
	ON UPDATE CASCADE 
	ON DELETE CASCADE
);

CREATE TABLE brands(
	id VARCHAR(255) PRIMARY KEY DEFAULT (UUID()),
	brand_code VARCHAR(100) UNIQUE NOT NULL,
	brand_name VARCHAR(255) CHARACTER SET UTF8MB4 COLLATE UTF8MB4_UNICODE_CI DEFAULT '',
	description VARCHAR(255) CHARACTER SET UTF8MB4 COLLATE UTF8MB4_UNICODE_CI DEFAULT ''
);

CREATE TABLE categories(
	id VARCHAR(255) PRIMARY KEY DEFAULT (UUID()),
	category_code VARCHAR(100) UNIQUE NOT NULL,
	category_name VARCHAR(255) CHARACTER SET UTF8MB4 COLLATE UTF8MB4_UNICODE_CI DEFAULT '',
	description VARCHAR(255) CHARACTER SET UTF8MB4 COLLATE UTF8MB4_UNICODE_CI DEFAULT ''
);

CREATE TABLE materials(
	id VARCHAR(255) PRIMARY KEY DEFAULT (UUID()),
	material_code VARCHAR(100) UNIQUE NOT NULL,
	material_name VARCHAR(255) CHARACTER SET UTF8MB4 COLLATE UTF8MB4_UNICODE_CI DEFAULT '',
	description VARCHAR(255) CHARACTER SET UTF8MB4 COLLATE UTF8MB4_UNICODE_CI DEFAULT ''
);

CREATE TABLE soles(
	id VARCHAR(255) PRIMARY KEY DEFAULT (UUID()),
	sole_code VARCHAR(100) UNIQUE NOT NULL,
	sole_name VARCHAR(255) CHARACTER SET UTF8MB4 COLLATE UTF8MB4_UNICODE_CI DEFAULT '',
	description VARCHAR(255) CHARACTER SET UTF8MB4 COLLATE UTF8MB4_UNICODE_CI DEFAULT ''
);

CREATE TABLE colors(
	id VARCHAR(255) PRIMARY KEY DEFAULT (UUID()),
	color_code VARCHAR(100) UNIQUE NOT NULL,
	color_name VARCHAR(255) CHARACTER SET UTF8MB4 COLLATE UTF8MB4_UNICODE_CI DEFAULT '',
	description VARCHAR(255) CHARACTER SET UTF8MB4 COLLATE UTF8MB4_UNICODE_CI DEFAULT ''
);

CREATE TABLE sizes(
	id VARCHAR(255) PRIMARY KEY DEFAULT (UUID()),
	size_code VARCHAR(100) UNIQUE NOT NULL,
	size_name VARCHAR(255) CHARACTER SET UTF8MB4 COLLATE UTF8MB4_UNICODE_CI DEFAULT '',
	description VARCHAR(255) CHARACTER SET UTF8MB4 COLLATE UTF8MB4_UNICODE_CI DEFAULT ''
);

CREATE TABLE coupons(
	id VARCHAR(255) PRIMARY KEY DEFAULT (UUID()),
	coupons_code VARCHAR(100) UNIQUE NOT NULL,
	coupons_name VARCHAR(255) CHARACTER SET UTF8MB4 COLLATE UTF8MB4_UNICODE_CI DEFAULT '',
	conditions DECIMAL(65,5) DEFAULT 0,
	coupons_price DECIMAL(65,5) DEFAULT 0,
	quantity INT DEFAULT 0,
	start_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	end_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	is_active TINYINT(1) DEFAULT 1
);

CREATE TABLE sales(
	id VARCHAR(255) PRIMARY KEY DEFAULT (UUID()),
	sale_code VARCHAR(100) UNIQUE NOT NULL,
	sale_name VARCHAR(255) CHARACTER SET UTF8MB4 COLLATE UTF8MB4_UNICODE_CI DEFAULT '',
	start_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	end_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	is_active TINYINT(1) DEFAULT 1
);

CREATE TABLE products(
	id VARCHAR(255) PRIMARY KEY DEFAULT (UUID()),
	product_code VARCHAR(100) UNIQUE NOT NULL,
	product_name VARCHAR(255) CHARACTER SET UTF8MB4 COLLATE UTF8MB4_UNICODE_CI DEFAULT '',
	id_brand VARCHAR(255) NOT NULL,
	id_category VARCHAR(255) NOT NULL,
	id_sole VARCHAR(255) NOT NULL,
	id_material VARCHAR(255) NOT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT FK_product_brand FOREIGN KEY(id_brand) REFERENCES brands(id) 
	ON UPDATE CASCADE 
	ON DELETE CASCADE,
	CONSTRAINT FK_product_category FOREIGN KEY(id_category) REFERENCES categories(id) 
	ON UPDATE CASCADE 
	ON DELETE CASCADE,
	CONSTRAINT FK_product_sole FOREIGN KEY(id_sole) REFERENCES soles(id) 
	ON UPDATE CASCADE 
	ON DELETE CASCADE,
	CONSTRAINT FK_product_material FOREIGN KEY(id_material) REFERENCES materials(id) 
	ON UPDATE CASCADE 
	ON DELETE CASCADE
);

CREATE TABLE product_images(
	id VARCHAR(255) PRIMARY KEY DEFAULT (UUID()),
	id_product VARCHAR(255) NOT NULL,
	images VARCHAR(255) DEFAULT '',
	CONSTRAINT FK_images_product FOREIGN KEY(id_product) REFERENCES products(id) 
	ON UPDATE CASCADE 
	ON DELETE CASCADE
);

CREATE TABLE product_details(
	id VARCHAR(255) PRIMARY KEY DEFAULT (UUID()),
	id_product VARCHAR(255) NOT NULL,
	id_color VARCHAR(255) NOT NULL,
	id_size VARCHAR(255) NOT NULL,
	weight FLOAT DEFAULT 0,
	price DECIMAL(65,5) DEFAULT 0,
	quantity INT DEFAULT 0,
	status VARCHAR(30) CHARACTER SET UTF8MB4 COLLATE UTF8MB4_UNICODE_CI DEFAULT '',
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT FK_productDetails_product FOREIGN KEY(id_product) REFERENCES products(id) 
	ON UPDATE CASCADE 
	ON DELETE CASCADE,
	CONSTRAINT FK_productDetails_color FOREIGN KEY(id_color) REFERENCES colors(id) 
	ON UPDATE CASCADE 
	ON DELETE CASCADE,
	CONSTRAINT FK_productDetails_size FOREIGN KEY(id_size) REFERENCES sizes(id) 
	ON UPDATE CASCADE 
	ON DELETE CASCADE
);

CREATE TABLE product_details_sales(
	id VARCHAR(255) PRIMARY KEY DEFAULT (UUID()),
	id_product_details VARCHAR(255) NOT NULL,
	id_sale VARCHAR(255) NOT NULL,
  	percent FLOAT DEFAULT 0,
	is_active TINYINT(1) DEFAULT 1,
	CONSTRAINT FK_history_sale_productDetails FOREIGN KEY(id_product_details) REFERENCES product_details(id) 
	ON UPDATE CASCADE 
	ON DELETE CASCADE,
	CONSTRAINT FK_history_sale_sales FOREIGN KEY(id_sale) REFERENCES sales(id) 
	ON UPDATE CASCADE 
	ON DELETE CASCADE
);

CREATE TABLE cart_details(
	id VARCHAR(255) PRIMARY KEY DEFAULT (UUID()),
	id_customer VARCHAR(255) NOT NULL,
	id_product_details VARCHAR(255) NOT NULL,
	quantity INT DEFAULT 0,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT FK_cart_customer FOREIGN KEY(id_customer) REFERENCES customers(id) 
	ON UPDATE CASCADE 
	ON DELETE CASCADE,
	CONSTRAINT FK_cart_productDetails FOREIGN KEY(id_product_details) REFERENCES product_details(id) 
	ON UPDATE CASCADE 
	ON DELETE CASCADE
);

CREATE TABLE orders(
	id VARCHAR(255) PRIMARY KEY DEFAULT (UUID()),
	order_code VARCHAR(100) UNIQUE NOT NULL,
	id_customer VARCHAR(255) NULL,
	id_staff VARCHAR(255) NOT NULL,
	id_coupons VARCHAR(255) NULL,
	customer_name VARCHAR(100) CHARACTER SET UTF8MB4 COLLATE UTF8MB4_UNICODE_CI DEFAULT '',
	phone_number VARCHAR(13) DEFAULT '',
	address VARCHAR(255) CHARACTER SET UTF8MB4 COLLATE UTF8MB4_UNICODE_CI DEFAULT '',
	transport_price DECIMAL(65,5) DEFAULT 0,
	reduced_price DECIMAL(65,5) DEFAULT 0,
	total_price DECIMAL(65,5) DEFAULT 0,
	total_payouts DECIMAL(65,5) DEFAULT 0,
	order_type VARCHAR(255) DEFAULT '',
	status VARCHAR(255) DEFAULT '',
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT FK_orders_customer FOREIGN KEY(id_customer) REFERENCES customers(id) 
	ON UPDATE CASCADE 
	ON DELETE CASCADE,
	CONSTRAINT FK_orders_staff FOREIGN KEY(id_staff) REFERENCES staffs(id) 
	ON UPDATE CASCADE 
	ON DELETE CASCADE,
	CONSTRAINT FK_orders_coupons FOREIGN KEY(id_coupons) REFERENCES coupons(id) 
	ON UPDATE CASCADE 
	ON DELETE CASCADE
);

CREATE TABLE order_details(
	id VARCHAR(255) PRIMARY KEY DEFAULT (UUID()),
	id_orders VARCHAR(255) NOT NULL,
	id_product_details VARCHAR(255) NOT NULL,
	quantity INT DEFAULT 0,
	total_price DECIMAL(65,5) DEFAULT 0,
	status VARCHAR(255) DEFAULT '',
	CONSTRAINT FK_orderDetails_productDetails FOREIGN KEY(id_product_details) REFERENCES product_details(id) 
	ON UPDATE CASCADE 
	ON DELETE CASCADE,
	CONSTRAINT FK_orderDetails_orders FOREIGN KEY(id_orders) REFERENCES orders(id) 
	ON UPDATE CASCADE 
	ON DELETE CASCADE
);

CREATE TABLE order_history(
	id VARCHAR(255) PRIMARY KEY DEFAULT (UUID()),
	id_orders VARCHAR(255) NOT NULL,
	description VARCHAR(255) CHARACTER SET UTF8MB4 COLLATE UTF8MB4_UNICODE_CI DEFAULT '',
	changed_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT FK_orderHistory_orders FOREIGN KEY(id_orders) REFERENCES orders(id) 
	ON UPDATE CASCADE 
	ON DELETE CASCADE
);


CREATE TABLE comments(
	id VARCHAR(255) PRIMARY KEY DEFAULT (UUID()),
	id_customer VARCHAR(255) NOT NULL,
	id_product_details VARCHAR(255) NOT NULL,
	id_orders VARCHAR(255) NOT NULL,
	comments VARCHAR(255) CHARACTER SET UTF8MB4 COLLATE UTF8MB4_UNICODE_CI DEFAULT '',
	CONSTRAINT FK_comments_customer FOREIGN KEY(id_customer) REFERENCES customers(id) 
	ON UPDATE CASCADE 
	ON DELETE CASCADE,
	CONSTRAINT FK_comments_productDetails FOREIGN KEY(id_product_details) REFERENCES product_details(id) 
	ON UPDATE CASCADE 
	ON DELETE CASCADE,
	CONSTRAINT FK_comments_orders FOREIGN KEY(id_orders) REFERENCES orders(id) 
	ON UPDATE CASCADE 
	ON DELETE CASCADE
);

ALTER TABLE orders 
ADD shipping_status VARCHAR(255) DEFAULT '';

ALTER TABLE orders 
ADD payment_method VARCHAR(255) DEFAULT '';

ALTER TABLE order_details 
ADD product_status VARCHAR(255) DEFAULT '';